filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "chatbot-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "chatbot-logs"
setup.template.pattern: "chatbot-logs-*"

logging.level: info
