---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 4
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: poojannpandyaa/chatbot:latest
        ports:
        - containerPort: 3000
        env:
        - name: OPENAI_API_HOST
          value: "https://api.groq.com/openai"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: OPENAI_API_KEY
        - name: OPENAI_API_MODEL
          value: "llama-3.3-70b-versatile"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
