input {
  beats {
    port => 5044
  }
  http {
    port => 5045
    codec => json
  }
}

output {
  if [type] == "rag_chat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "rag-logs-%{+YYYY.MM.dd}"
      data_stream => "false"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "chatbot-logs-%{+YYYY.MM.dd}"
      action => "create"
    }
  }
}
