---
- name: Pull chatbot Docker image
  community.docker.docker_image:
    name: "poojannpandyaa/chatbot:latest"
    source: pull
- name: Remove existing chatbot container
  community.docker.docker_container:
    name: chatbot
    state: absent
- name: Run chatbot container
  community.docker.docker_container:
    name: chatbot
    image: "poojannpandyaa/chatbot:latest"
    state: started
    ports:
      - "3000:3000"
